### ISSUE TITLE
Does not work on FreeBSD

### ISSUE THREAD

**Issue by matt-bsd** [cirala/vifm_devicons#3]
Hello, these icons do not work on FreeBSD vifm _at all_ and I have no idea why, where should I start with debugging this? As shown on the images below, after adding devicons to vifmrc, or sourcing the devicons file, I can see, that in vifm, all the file/direcotry names move slightly to the right, as if there was an icon next to them, but there isn't any. No idea where to start. I have the fonts installed, for example "lsd" command shows pretty icons, no problems there. I can also paste the icons into console and they get shown correctly. By default, I use xterm, I tried also alacritty, and urxvt, no change.
![scrot-20-1115-13:28:40](https://user-images.githubusercontent.com/74494265/99184878-86576300-2746-11eb-80be-a2e5aa9a78fc.png)

**Comment by JozanLeClerc** [comment]
Hi, I had the same issue on FreeBSD 12.2 and 12.1-RELEASE as well as some other curses programs errors (unwanted characters in abook, ncpamixer and calcurse, crashes on tremc, and a lot more). After a full reinstall on 13.0-RELEASE all of these and the icons issue in vifm are fixed now, with everything built from ports. I would suggest upgrading.

**Comment by matt-bsd** [comment]
Yes, this issue got autoresolved by upgrading. I upgraded with pkg.
